### ISSUE TITLE
Slackbot / GitHub PR Bot integration

### ISSUE THREAD

**Issue by Frankie-Boy** [novoda/github-slack-action#1]
**BOT SUCCESS MESSAGE JSON:**

`{
    "attachments": {
			"text": {
				"type": "mrkdwn",
				"color": "#36a64f",
				"text": "<https://github.com|GitHub PR Bot> \n Bad News! \n Your PR is on fire :scream: :fire:"     				}
			}
}`

**Comment by zegnus** [comment]
👍 will have a look at it, thanks!

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
